import 'package:flutter/material.dart';

class AppIcons {
  static const Map<String, IconData> icons = {
    // General
    'home': Icons.home_outlined,
    'work': Icons.work_outline,
    'person': Icons.person_outline,
    'settings': Icons.settings_outlined,
    'search': Icons.search,
    'favorite': Icons.favorite_border,
    'star': Icons.star_border,
    'menu': Icons.menu,
    'close': Icons.close,
    'add': Icons.add,
    'check': Icons.check,
    'info': Icons.info_outline,
    'help': Icons.help_outline,
    'warning': Icons.warning_amber_rounded,
    'error': Icons.error_outline,
    'delete': Icons.delete_outline,
    'edit': Icons.edit_outlined,
    'share': Icons.share_outlined,
    'save': Icons.save_outlined,
    'download': Icons.download_outlined,
    'upload': Icons.upload_outlined,
    'refresh': Icons.refresh,
    'filter': Icons.filter_list,
    'sort': Icons.sort,
    'list': Icons.list,
    'grid': Icons.grid_view,
    'more_vert': Icons.more_vert,
    'more_horiz': Icons.more_horiz,
    'arrow_back': Icons.arrow_back,
    'arrow_forward': Icons.arrow_forward,
    'arrow_up': Icons.arrow_upward,
    'arrow_down': Icons.arrow_downward,
    'chevron_left': Icons.chevron_left,
    'chevron_right': Icons.chevron_right,

    // Finance & Money
    'money': Icons.attach_money,
    'wallet': Icons.account_balance_wallet_outlined,
    'bank': Icons.account_balance_outlined,
    'credit_card': Icons.credit_card_outlined,
    'receipt': Icons.receipt_long_outlined,
    'savings': Icons.savings_outlined,
    'trending_up': Icons.trending_up,
    'trending_down': Icons.trending_down,
    'pie_chart': Icons.pie_chart_outline,
    'bar_chart': Icons.bar_chart,
    'show_chart': Icons.show_chart,
    'calculate': Icons.calculate_outlined,
    'currency_exchange': Icons.currency_exchange,
    'payment': Icons.payment_outlined,
    'shopping': Icons.shopping_bag_outlined,
    'shopping_bag': Icons.shopping_bag_outlined,
    'shopping_cart': Icons.shopping_cart_outlined,
    'sell': Icons.sell_outlined,
    'price_check': Icons.price_check,
    'money_off': Icons.money_off_outlined,

    // Transport
    'directions_car': Icons.directions_car_outlined,
    'directions_bus': Icons.directions_bus_outlined,
    'directions_bike': Icons.directions_bike_outlined,
    'directions_walk': Icons.directions_walk,
    'directions_run': Icons.directions_run,
    'flight': Icons.flight,
    'train': Icons.train_outlined,
    'local_taxi': Icons.local_taxi_outlined,
    'local_gas_station': Icons.local_gas_station_outlined,
    'local_parking': Icons.local_parking_outlined,
    'commute': Icons.commute_outlined,
    'electric_car': Icons.electric_car_outlined,
    'electric_scooter': Icons.electric_scooter_outlined,
    'electric_bike': Icons.electric_bike_outlined,
    'moped': Icons.moped_outlined,
    'pedal_bike': Icons.pedal_bike_outlined,
    'airport_shuttle': Icons.airport_shuttle_outlined,
    'agriculture': Icons.agriculture_outlined,
    'sailing': Icons.sailing_outlined,
    'snowmobile': Icons.snowmobile_outlined,

    // Food & Drink
    'restaurant': Icons.restaurant_outlined,
    'restaurant_menu': Icons.restaurant_menu_outlined,
    'fastfood': Icons.fastfood_outlined,
    'local_cafe': Icons.local_cafe_outlined,
    'local_bar': Icons.local_bar_outlined,
    'local_pizza': Icons.local_pizza_outlined,
    'local_dining': Icons.local_dining_outlined,
    'lunch_dining': Icons.lunch_dining_outlined,
    'breakfast_dining': Icons.breakfast_dining_outlined,
    'dinner_dining': Icons.dinner_dining_outlined,
    'coffee': Icons.coffee_outlined,
    'liquor': Icons.liquor_outlined,
    'bakery_dining': Icons.bakery_dining_outlined,
    'icecream': Icons.icecream_outlined,
    'ramen_dining': Icons.ramen_dining_outlined,
    'kitchen': Icons.kitchen_outlined,
    'cake': Icons.cake_outlined,
    'wine_bar': Icons.wine_bar_outlined,
    'tapas': Icons.tapas_outlined,
    'rice_bowl': Icons.rice_bowl_outlined,

    // Health & Wellness
    'fitness_center': Icons.fitness_center_outlined,
    'spa': Icons.spa_outlined,
    'pool': Icons.pool_outlined,
    'medical_services': Icons.medical_services_outlined,
    'local_hospital': Icons.local_hospital_outlined,
    'local_pharmacy': Icons.local_pharmacy_outlined,
    'healing': Icons.healing_outlined,
    'monitor_heart': Icons.monitor_heart_outlined,
    'psychology': Icons.psychology_outlined,
    'medication': Icons.medication_outlined,
    'health_and_safety': Icons.health_and_safety_outlined,
    'clean_hands': Icons.clean_hands_outlined,
    'sanitizer': Icons.sanitizer_outlined,
    'sick': Icons.sick_outlined,
    'masks': Icons.masks_outlined,
    'coronavirus': Icons.coronavirus_outlined,
    'vaccines': Icons.vaccines_outlined,
    'bloodtype': Icons.bloodtype_outlined,

    // Entertainment & Leisure
    'movie': Icons.movie_outlined,
    'theaters': Icons.theaters_outlined,
    'music_note': Icons.music_note_outlined,
    'headphones': Icons.headphones_outlined,
    'sports_esports': Icons.sports_esports_outlined,
    'sports_soccer': Icons.sports_soccer_outlined,
    'sports_basketball': Icons.sports_basketball_outlined,
    'sports_tennis': Icons.sports_tennis_outlined,
    'sports_golf': Icons.sports_golf_outlined,
    'casino': Icons.casino_outlined,
    'extension': Icons.extension_outlined,
    'palette': Icons.palette_outlined,
    'brush': Icons.brush_outlined,
    'camera_alt': Icons.camera_alt_outlined,
    'image': Icons.image_outlined,
    'videogame_asset': Icons.videogame_asset_outlined,
    'toys': Icons.toys_outlined,
    'sports_football': Icons.sports_football_outlined,
    'sports_baseball': Icons.sports_baseball_outlined,
    'sports_volleyball': Icons.sports_volleyball_outlined,
    'sports_cricket': Icons.sports_cricket_outlined,
    'sports_mma': Icons.sports_mma_outlined,
    'sports_motorsports': Icons.sports_motorsports_outlined,
    'sports_rugby': Icons.sports_rugby_outlined,
    'kitesurfing': Icons.kitesurfing_outlined,
    'snowboarding': Icons.snowboarding_outlined,

    // Household & Living
    'home_repair_service': Icons.home_repair_service_outlined,
    'cleaning_services': Icons.cleaning_services_outlined,
    'lightbulb': Icons.lightbulb_outline,
    'water_drop': Icons.water_drop_outlined,
    'electrical_services': Icons.electrical_services_outlined,
    'chair': Icons.chair_outlined,
    'bed': Icons.bed_outlined,
    'weekend': Icons.weekend_outlined,
    'living': Icons.living_outlined,
    'bedroom_parent': Icons.bedroom_parent_outlined,
    'bedroom_baby': Icons.bedroom_baby_outlined,
    'bathroom': Icons.bathroom_outlined,
    'table_restaurant': Icons.table_restaurant_outlined,
    'window': Icons.window_outlined,
    'roofing': Icons.roofing_outlined,
    'fence': Icons.fence_outlined,
    'balcony': Icons.balcony_outlined,
    'yard': Icons.yard_outlined,

    // Education & Work
    'school': Icons.school_outlined,
    'menu_book': Icons.menu_book_outlined,
    'book': Icons.book_outlined,
    'library_books': Icons.library_books_outlined,
    'science': Icons.science_outlined,
    'computer': Icons.computer_outlined,
    'laptop': Icons.laptop_mac_outlined,
    'smartphone': Icons.smartphone_outlined,
    'tablet': Icons.tablet_mac_outlined,
    'business_center': Icons.business_center_outlined,
    'meeting_room': Icons.meeting_room_outlined,
    'work_history': Icons.work_history_outlined,
    'engineering': Icons.engineering_outlined,
    'architecture': Icons.architecture_outlined,
    'construction': Icons.construction_outlined,
    'precision_manufacturing': Icons.precision_manufacturing_outlined,
    'plumbing': Icons.plumbing_outlined,
    'handyman': Icons.handyman_outlined,
    'carpenter': Icons.carpenter_outlined,

    // Travel & Places
    'map': Icons.map_outlined,
    'place': Icons.place_outlined,
    'location_city': Icons.location_city_outlined,
    'beach_access': Icons.beach_access_outlined,
    'park': Icons.park_outlined,
    'hotel': Icons.hotel_outlined,
    'luggage': Icons.luggage_outlined,
    'explore': Icons.explore_outlined,
    'tour': Icons.tour_outlined,
    'festival': Icons.festival_outlined,
    'temple_buddhist': Icons.temple_buddhist_outlined,
    'temple_hindu': Icons.temple_hindu_outlined,
    'church': Icons.church_outlined,
    'mosque': Icons.mosque_outlined,
    'synagogue': Icons.synagogue_outlined,
    'castle': Icons.castle_outlined,
    'fort': Icons.fort_outlined,

    // Shopping & Gifts
    'card_giftcard': Icons.card_giftcard_outlined,
    'redeem': Icons.redeem_outlined,
    'loyalty': Icons.loyalty_outlined,
    'store': Icons.store_outlined,
    'storefront': Icons.storefront_outlined,
    'shopping_basket': Icons.shopping_basket_outlined,
    'production_quantity_limits': Icons.production_quantity_limits_outlined,
    'inventory_2': Icons.inventory_2_outlined,
    'warehouse': Icons.warehouse_outlined,

    // Misc
    'pets': Icons.pets_outlined,
    'child_care': Icons.child_care_outlined,
    'child_friendly': Icons.child_friendly_outlined,
    'face': Icons.face_outlined,
    'fingerprint': Icons.fingerprint,
    'lock': Icons.lock_outline,
    'visibility': Icons.visibility_outlined,
    'visibility_off': Icons.visibility_off_outlined,
    'calendar_today': Icons.calendar_today_outlined,
    'event': Icons.event_outlined,
    'schedule': Icons.schedule_outlined,
    'timer': Icons.timer_outlined,
    'watch': Icons.watch_outlined,
    'watch_later': Icons.watch_later_outlined,
    'alarm': Icons.alarm_outlined,
    'hourglass_empty': Icons.hourglass_empty_outlined,
    'hourglass_full': Icons.hourglass_full_outlined,
    'update': Icons.update,
    'history': Icons.history,
    'manage_history': Icons.manage_history_outlined,
    'bug_report': Icons.bug_report_outlined,
    'report': Icons.report_outlined,
    'flag': Icons.flag_outlined,
    'outlined_flag': Icons.outlined_flag,
    'label': Icons.label_outline,
    'label_important': Icons.label_important_outline,
    'bookmark': Icons.bookmark_outline,
    'bookmark_border': Icons.bookmark_border,
  };

  static IconData? getIcon(String name) {
    return icons[name];
  }
}
